dotenv: .env
dependancies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
networks:
  rinkeby:
    eth_usd_pricefeed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
